config/routes.rb
Rails.application.routes.draw do
  #devise_for :users
  # root :to => "live_shows#index"
  root :to => "live_shows#index"
  mount ActionCable.server => "/cable"
  resources :homes do
    collection do

      get :g_index

    end
  end
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  namespace :api, :defaults => { :format => :json } do
    post "login" => "auth#login"
    post "logout" => "auth#logout"
    resources :users do
      post "picture_upload"
    end
    resources :live_shows do
      resources :followings
      resources :chats do
        get "latest_chats"
      end
      resources :questions do
        resources :askings
      end
    end
  end
  resources :users
  resources :live_shows do
    resources :followings
    resources :chats
    resources :questions do
      resources :askings, :only => [:create, :destroy]
    end
  end


  get '/g_index' => 'homes#g_index' , :as => 'g_index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/live_show.rb
class LiveShow < ApplicationRecord
  belongs_to :user
  has_many :chats, dependent: :destroy
  has_many :questions
  has_many :watchings
  has_many :watchers, :through => :watchings, :source => :user
  has_many :likes, :dependent => :destroy
  has_many :liked_chats, :through => :likes ,:source => :chat

  def return_json
    {
      :live_show => self,
      :live_show_user => self.user,
      #:live_show_chats => self.chats,
      #:live_show_questions => self.questions,
      :live_show_watchers => self.watchers,
      :user_followers_count => self.user.followers.count
    }
  end
end

app/controllers/api/live_shows_controller.rb
class Api::LiveShowsController < Api::ApiController
  before_action :authenticate_user!
  def index
    @live_shows = LiveShow.includes(:user)
    render :json => {
      :live_shows => @live_shows.map{|i|i.return_json}
    }
  end

  def show
    #@user = User.find(params[:id])
    @live_show = LiveShow.find(params[:id])
    #@live_shows = @user.live_shows
    render :json => {
      :live_show => @live_show.return_json,
      :live_show_chats => @live_show.chats.map{|i|i.return_json},
      :live_show_questions => @live_show.questions.map{|i|i.return_json},
    }
  end

  def create
    #@user = current_user
    #@live_show.user_id = @user.id
    #不確定current_user是否能這樣用
    @fb_url = params[:fb_url].split('"').second
    @live_show = LiveShow.new(name: params[:name],
                              user_id: current_user.id,
                              fb_url: @fb_url )
    if @live_show.save
      render :json => {
        :status => 200,
        :message => "create succeed",
        :live_show => @live_show
      }
    else
      render :json => {
             :status => 401,
             :message => "create failed"
      }
    end
  end

  def update
    @live_show = LiveShow.find(params[:id])
    @live_show.update(name:params[:name])
    if @live_show.save
      render :json => {
        :status => 200,
        :message => "update succeed",
        :live_show => @live_show
      }
    else
      render :json => {
             :status => 401,
             :message => "update failed"
      }
    end
  end

  def destroy
    @live_show = LiveShow.find(params[:id])
    if @live_show.destroy
      render :json => {
        :status => 200,
        :message => "destroy succeed"
      }
    else
      render :json => {
        :status => 401,
        :message => "destroy failed"
      }
    end
  end

  # private
  # def live_show_params
  #   params.require(:live_show).permit(:name, :user_id)
  # end
end

app/controllers/live_shows_controller.rb
class LiveShowsController < ApplicationController
  def index
    @live_shows = LiveShow.order("id DESC").includes(:user)
  end

  def show
    @live_show = LiveShow.find(params[:id])
    @user = @live_show.user
    @live_shows = @user.live_shows
    @question = Question.new
  end

end

app/views/live_shows/index.html.erb
<div class="index_navtab">
	<ul class="nav nav-tabs">
		<li><a data-toggle="tab" href="#home">熱門直播</a></li>
		<!-- <li><a data-toggle="tab" href="#menu1">熱門直播</a></li> -->
	</ul>
</div>
<div class="tab-content">
	<div id="home" class="tab-pane fade in active">
	<br>
		<div class="channel_row">
		    <div class="col-lg-12">
		    <% @live_shows.each do |l| %>
		    	<!-- <a href="<%#= user_live_show_path(l.user,l) %>"> -->
		    	<%#= link_to "5566",live_show_path(l) %>
					<div class="channel_item">
					<!-- <a id="channel_item_a" href="<%= live_show_path(l) %>"> -->
						<div class="channel_pic">
							<!-- <img src="http://s2.post01.com/uploads/c4/b/119050/14689381446338.jpg"> -->
							<%= image_tag l.user.picture.url %>
						</div>
						<div class="channel_about">
							<div class="channel_about_top">
								<div class="channel_owner">
									<span class="glyphicon glyphicon-user" aria-hidden="true"> <%= l.user.fb_name %></span>
								</div>
								<div class="channel_count">
									<span class="glyphicon glyphicon-eye-open" aria-hidden="true"> 5人觀看</span>
								</div>
							</div>
							<div class="channel_about_bottom">
								<div class="channel_name"><%= l.name %></div>
								<div class="channel_content"><%= l.user.description %>
								</div>
							</div>
							<div class="live_shows_bt" onclick="location.href='<%= live_show_path(l)%>';">
								<p>進入直播室</p>
							</div>
						</div>
					</div>
			<% end %>
				<!-- <div class="channel_item">
					<div class="channel_pic">
						<img src="http://img.gq.com.tw/userfiles/sm/sm645_images_A1/21012/2015020266774337.jpg">
					</div>
					<div class="channel_about">
						<div class="channel_about_top">
							<div class="channel_owner">
								<span class="glyphicon glyphicon-user" aria-hidden="true"> aaaa</span>
							</div>
							<div class="channel_count">
								<span class="glyphicon glyphicon-eye-open" aria-hidden="true"> 5人觀看</span>
							</div>
						</div>
						<div class="channel_about_bottom">
							<div class="channel_name">台灣分隊長</div>
							<div class="channel_content">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eum cumque, asperiores libero sint iste aliquam. Accusantium minima, aliquam excepturi fugit dignissimos quasi inventore beatae esse, commodi repellendus maxime recusandae ipsam.
							</div>
						</div>
					</div>
				</div>
				<div class="channel_item">
					<div class="channel_pic">
						<img src="http://www.daliulian.net/imgs/image/10/1093836.jpg">
					</div>
					<div class="channel_about">
						<div class="channel_about_top">
							<div class="channel_owner">
								<span class="glyphicon glyphicon-user" aria-hidden="true"> aaaa</span>
							</div>
							<div class="channel_count">
								<span class="glyphicon glyphicon-eye-open" aria-hidden="true"> 5人觀看</span>
							</div>
						</div>
						<div class="channel_about_bottom">
							<div class="channel_name">台灣分隊長</div>
							<div class="channel_content">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eum cumque, asperiores libero sint iste aliquam. Accusantium minima, aliquam excepturi fugit dignissimos quasi inventore beatae esse, commodi repellendus maxime recusandae ipsam.
							</div>
						</div>
					</div>
				</div> -->
		    </div>
		</div>
	</div>
	<!-- <div id="menu1" class="tab-pane fade">
	<br>
	  <div class="channel_row">
		    <div class="col-lg-12">
				<div class="channel_item">
					<div class="channel_pic">
						<img src="http://s2.post01.com/uploads/c4/b/119050/14689381446338.jpg">
					</div>
					<div class="channel_about">
						<div class="channel_about_top">
							<div class="channel_owner">
								<span class="glyphicon glyphicon-user" aria-hidden="true"> aaaa</span>
							</div>
							<div class="channel_count">
								<span class="glyphicon glyphicon-eye-open" aria-hidden="true"> 5人觀看</span>
							</div>
						</div>
						<div class="channel_about_bottom">
							<div class="channel_name">台灣分隊長</div>
							<div class="channel_content">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eum cumque, asperiores libero sint iste aliquam. Accusantium minima, aliquam excepturi fugit dignissimos quasi inventore beatae esse, commodi repellendus maxime recusandae ipsam.
							</div>
						</div>
					</div>
				</div>
				<div class="channel_item">
					<div class="channel_pic">
						<img src="http://img.gq.com.tw/userfiles/sm/sm645_images_A1/21012/2015020266774337.jpg">
					</div>
					<div class="channel_about">
						<div class="channel_about_top">
							<div class="channel_owner">
								<span class="glyphicon glyphicon-user" aria-hidden="true"> aaaa</span>
							</div>
							<div class="channel_count">
								<span class="glyphicon glyphicon-eye-open" aria-hidden="true"> 5人觀看</span>
							</div>
						</div>
						<div class="channel_about_bottom">
							<div class="channel_name">台灣分隊長</div>
							<div class="channel_content">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eum cumque, asperiores libero sint iste aliquam. Accusantium minima, aliquam excepturi fugit dignissimos quasi inventore beatae esse, commodi repellendus maxime recusandae ipsam.
							</div>
						</div>
					</div>
				</div>
				<div class="channel_item">
					<div class="channel_pic">
						<img src="http://www.daliulian.net/imgs/image/10/1093836.jpg">
					</div>
					<div class="channel_about">
						<div class="channel_about_top">
							<div class="channel_owner">
								<span class="glyphicon glyphicon-user" aria-hidden="true"> aaaa</span>
							</div>
							<div class="channel_count">
								<span class="glyphicon glyphicon-eye-open" aria-hidden="true"> 5人觀看</span>
							</div>
						</div>
						<div class="channel_about_bottom">
							<div class="channel_name">台灣分隊長</div>
							<div class="channel_content">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eum cumque, asperiores libero sint iste aliquam. Accusantium minima, aliquam excepturi fugit dignissimos quasi inventore beatae esse, commodi repellendus maxime recusandae ipsam.
							</div>
						</div>
					</div>
				</div>
		    </div>
		</div>
	</div> -->
</div>

app/views/live_shows/show.html.erb
<%#= image_tag @user.fb_image %>
<%#= @user.fb_name %>
<%#= @live_show.name %>
<%#= @user.description %>
<%#= @user.fb_name %>

<%# @live_shows.each do |l| %>
  <%#= l.name %>
  <%#= link_to "進入直播室", live_show_path(l) %>
<%# end %>
<script type="text/javascript">
function add() {
    var now = new Date();
    var div = document.getElementById('live_talk_word');
    div.scrollTop = div.scrollHeight;
}
$('.live_talk_word').css({
    "overflow-y": "hidden"
})
$(".live_talk_word").on("mouseenter mouseleave", function(event) {
    if (event.type == "mouseenter") {
        $(this).css({
            "overflow-y": "auto"
        }); //滑鼠進入
    }
});
// window.onload = function() {
//     add();
// }
window.current_user_id = <%= current_user.id %>
window.live_show_id = <%= @live_show.id %>

</script>
<script src="/ccc/js/progress-ring.js"></script>
<script> $('.progress-ring').loadingRing(); </script>
<div class="container">
    <div class="channel_row">
        <div class="col-lg-12">
            <div class="live_top">
                <div class="live_top_top">
                    <div class="live_name">
                        <h4><%= @live_show.name %></h4>
                    </div>
                    <!--                     <div class="live_follow">追隨</div> -->
                    <!-- <div class="progress progress-striped active">
                        <div class="progress-bar progress-bar-warning" style="width:80%">
                        </div>
                    </div> -->
                    <!-- <div class="fb-video" data-href= "<%= @live_show.fb_url %>" data-width="650" data-height="400" data-show-text="false">
                          <blockquote cite="https://www.facebook.com/naruko.tw/videos/10154012016058862/" class="fb-xfbml-parse-ignore"></blockquote>
                      </div> -->
                    <div class="fb-video" data-width="650" data-height="400" data-show-text="false">

                     <iframe src="<%= @live_show.fb_url.try(:html_safe) %>" width="650" height="400" frameborder="0"></iframe>
                    </div>
                    <div class="live_talk">
                        <div class="show_navtab">
                            <ul class="nav nav-tabs">
                                <li><a data-toggle="tab" href="#qa">問問題</a></li>
                                <li><a data-toggle="tab" href="#qa">聊天室</a></li>
                            </ul>
                        </div>

                        <div id="qa" class="tab-pane fade in active">
                            <div id="live_talk_word" class="live_talk_word">
                                <table id="live_talk_table" class="table">
                                    <% @live_show.questions.all.order("users_count DESC").each do |m| %>
                                        <tr data-questionid="<%= m.id %>">
                                            <td id="count_question_<%=m.id%>" class="user_count_td">
                                                <div class="progress-ring" data-percent="<%=m.users_count%>"></div>
                                            </td>
                                                <!-- <td><%=m.users_count%></td> -->
                                                <td class="live_talk_r">

                                                    <img class='imggg2' src='<%=m.user.fb_image%>'>
                                                    <span><%= m.user.fb_name %>:
                                                    </span><br>
                                                    <p><%= m.subject %></p>
                                                </td>
                                                <td class="like_btn_box" data-questionid="<%= m.id %>" data-userid="<%= m.user.try(:id) %>"
                                                 id="td_like_<%= m.id %>">
                                                    <%= link_to "", live_show_question_askings_path(@live_show, m),:class =>"glyphicon glyphicon-plus like_plus", :method => :post %>
                                                </td>
                                        </tr>

                                    <% end %>
                                </table>
                            </div>
                        </div>
                        <div id="tk" class="tab-pane fade">
                            <div id="talk_list"></div>
                        </div>
                        <div class="live_talk_submit">
                            <%= form_for [@live_show,@question], :remote => true do |f| %>
                                <input type="hidden" name="live_show" value="<%= @live_show.id %>">
                                <div class="input-group">
                                  <%= f.text_field :subject,:id =>'content',:placeholder => "輸入想問直播主的問題......",:class => "form-control"%>
                                  <span class="input-group-btn">
                                    <%= f.submit "送出",:id =>"talk_submit",:onclick => "add()" ,:class => "btn btn-default"%>
                                  </span>
                                </div>

                                        <% end %>
                        </div>

                    </div>
                </div>
                <br>
                <div class="live_bottom">
                    <div class="border_up">
                        <h3><%= @user.fb_name %> 的頻道</h3>
                    </div>
                    <div class="live_bottom_a">
                        <div class="live_pic">
                            <img src="http://s2.post01.com/uploads/c4/b/119050/14689381446338.jpg">
                        </div>
                        <div class="live_contant">
                            <%= @user.description %>
                        </div>
                    </div>
                    <div class="border_down">
                        <h3><%= @user.fb_name %> 的影片</h3>
                    </div>
                    <div class="live_bottom_b">
                    <%# @live_shows.each do |l| %>
                            <%#= l.name %>
                                <%#= link_to "進入直播室", live_show_path(l) %>
                                    <%# end %>
                        <div class="live_bottom_b_box">
                            <div class="live_bottom_b_item">
                                <img src="http://s2.post01.com/uploads/c4/b/119050/14689381446338.jpg">
                                <div class="live_bottom_b_words">
                                    <p>舉重訓練 Part 1</p>
                                    <p>直播時間:2016/10/5</p>
                                </div>
                            </div>
                            <div class="live_bottom_b_item">
                                <img src="http://s2.post01.com/uploads/c4/b/119050/14689381446338.jpg">
                                <div class="live_bottom_b_words">
                                    <p>舉重訓練 Part 2</p>
                                    <p>直播時間:2016/10/5</p>
                                </div>
                            </div>
                            <div class="live_bottom_b_item">
                                <img src="http://s2.post01.com/uploads/c4/b/119050/14689381446338.jpg">
                                <div class="live_bottom_b_words">
                                    <p>舉重訓練 Part 3</p>
                                    <p>直播時間:2016/10/5</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <%# @live_shows.each do |l| %>
                        <%#= l.name %>
                            <%#= link_to "進入直播室", live_show_path(l) %>
                                <%# end %>
                </div>
            </div>
        </div>
    </div>
</div>
    <!-- <script src="/ccc/js/jquery-2.1.1.min.js"></script> -->
    <!-- <script src="/ccc/js/progress-ring.js"></script> -->
<script type="text/javascript">
    $(".container").on("click", ".like_btn_box", function(e){
        e.preventDefault(); e.stopPropagation();
        var questionId = $(this).data("questionid");
        var userId = $(this).data("userid");
            //     var questionIds = questionId;
            //     var userIds = userId;
            //     var live_showId = live_show_id;
            //     var askingIds = askingId;
        setLike(questionId, userId);
    })

</script>
<script>
$(".progress-ring").loadingRing();
</script>
<div id="fb-root"></div>
<script>(function(d, s, id) {
 var js, fjs = d.getElementsByTagName(s)[0];
 if (d.getElementById(id)) return;
 js = d.createElement(s); js.id = id;
 js.src = "//connect.facebook.net/zh_TW/sdk.js#xfbml=1&version=v2.8&appId=636280343220058";
 fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>