config/routes.rb
Rails.application.routes.draw do
  #devise_for :users
  # root :to => "live_shows#index"
  root :to => "live_shows#index"
  mount ActionCable.server => "/cable"
  resources :homes do
    collection do

      get :g_index

    end
  end
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  namespace :api, :defaults => { :format => :json } do
    post "login" => "auth#login"
    post "logout" => "auth#logout"
    resources :users do
      post "picture_upload"
    end
    resources :live_shows do
      resources :followings
      resources :chats do
        get "latest_chats"
      end
      resources :questions do
        resources :askings
      end
    end
  end
  resources :users
  resources :live_shows do
    resources :followings
    resources :chats
    resources :questions do
      resources :askings, :only => [:create, :destroy]
    end
  end


  get '/g_index' => 'homes#g_index' , :as => 'g_index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Sportfly</title>
    <link rel="shortcut icon" href="/css/img/logo.png">

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag '/css/layout_min', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    '/ccc/css/progress-ring', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <nav class="navbar navbar-default" role="navigation">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
          <span class="sr-only">選單切換</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <div class="navbar_logo">
          <a class="navbar-brand" href="/live_shows#index">
          <%= image_tag "/css/img/logo.png" %>
          </a>
        </div>
      </div>

      <!-- 手機隱藏選單區 -->
      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <!-- 左選單 -->
        <ul class="nav navbar-nav">
          <!-- <li><a href="#"></a></li> -->
        </ul>

        <!-- 右選單 -->
        <div>

        <ul id="nav_words" class="nav navbar-nav navbar-right">

        <!-- 搜尋表單 -->
          <!-- <li>
            <form class="navbar-form" role="search">
              <div class="form-group">
                <input type="text" class="form-control" placeholder="請輸入關鍵字">
              </div>
              <button type="submit" class="btn btn-default">搜尋</button>
            </form>
          </li> -->


        <% if current_user %>
          <li><p class="user_name"><%=current_user.fb_name%></p></li> 
          <li><%= link_to('登出', destroy_user_session_path, :method => :delete) %></li>
        <% else %>
          <li><p class="user_name">訪客 您好！！</p></li> 
          <li><%= link_to "登入 Facebook", user_facebook_omniauth_authorize_path %></li>
        <% end %>

          <!-- <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">繁體中文 <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><a href="#">繁體中文</a></li>
              <li><a href="#">English</a></li>
              <li><a href="#">日本語</a></li>
            </ul>
          </li> -->
        </ul>
      </div>
      <!-- 手機隱藏選單區結束 -->
    </nav>
    <div class="container">
      <%# if current_user %>
        <%#= link_to('登出', destroy_user_session_path, :method => :delete) %>
      <%#= link_to('修改密碼', edit_registration_path(:user)) %>
      <%# else %>
        <%#= link_to('註冊', new_registration_path(:user)) %>
        <%#= link_to('登入', new_session_path(:user)) %>
      <%# end %>
      <div class="col-sm-12">
        <%if flash[:notice].present?%>
          <div class="alert alert-success" role="alert">
            <p style="color: green"><%=flash[:notice] %></p>
          </div>
      </div>
      <%end%>
      <div class="col-sm-12">
        <%if flash[:alert].present?%>
          <div class="alert alert-danger" role="alert">
            <p style="color: red"><%=flash[:alert] %></p>
          </div>
        <%end%>
      </div>
      <!-- <span class="login">
        <%# if current_user %>
          <%#= link_to "登出", auth_signout_path, :method => :post %>
          <%#= current_user.name %>
          <%#= image_tag( current_user.fb_image ) %>
        <%# else %>
          <a href="/auth/facebook">Facebook 登入</a>
        <%# end %>
        <%# if current_user %>
          <%#= link_to('登出', destroy_user_session_path, :method => :delete) %>
        <%# else %>
            <%#= link_to "登入 Facebook", user_facebook_omniauth_authorize_path %>
        <%# end %>
      </span> -->
      <%= yield %>
    </div>

  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html lang="">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Sportfly - Live & Transform!</title>
    <!-- Bootstrap Core CSS -->
    <link href="sportfly/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom Fonts -->
    <!-- <link href="sportfly/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"> -->
    <script src="https://use.fontawesome.com/f70cd2541a.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>
    <!-- Theme CSS -->
    <link href="sportfly/css/agency.min.css" rel="stylesheet">
    <link href="http://fonts.googleapis.com/earlyaccess/notosanstc.css" rel="stylesheet">
    <link href="sportfly/css/other.css" rel="stylesheet">
    <link href="sportfly/js/mobile.js" rel="javascript" type="text/javascript">

		<!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->
	</head>
	<body>

		<%= yield %>


		<<script src="sportfly/vendor/jquery/jquery.min.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="sportfly/vendor/bootstrap/js/bootstrap.min.js"></script>
    <!-- Plugin JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
    <!-- Contact Form JavaScript -->
    <script src="sportfly/js/jqBootstrapValidation.js"></script>
    <script src="sportfly/js/contact_me.js"></script>
    <!-- Theme JavaScript -->
    <script src="sportfly/js/agency.min.js"></script>
    <script src="http://libs.baidu.com/jquery/2.0.0/jquery.min.js"></script>
    <script type="text/javascript" src="js/jquery.typetype.js"></script>
	</body>
</html>